### PR TITLE
Added functionality for rendering articles via their IS. Either throu…

### PR DESCRIPTION
**Pull request by Fandasuba**
…gh clicking an article card or via endpoint handling.

### CODE REVIEW

**Comment by Fandasuba** [comment]
Also did some minor CSS changes since I'm now mind-controlled by CSS design. Will likely continue tweaking as the tasks roll on.

**Comment by Fandasuba** [comment]
Sorry team... i forgot to remove console logs again :(

**Comment by nc-aimee-muter** [comment]
It's like you knew I was going to mention the console logs 😂

The single article page is looking good! It's nicely responsive too!
Please add some loading feedback to this page. All I can see is "trouble loading article" but that takes a while to appear. I'd like to know that the article is loading straight away.

**Comment by nc-aimee-muter** [comment]
I forgot to add... please format your dates so that they are more user-friendly.

**Pull request merged**
